services:
  db:
    image: postgres:15-alpine
    container_name: nikonet_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nikonet
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/sql:/docker-entrypoint-initdb.d # Corre los scripts .sql al iniciar
    restart: unless-stopped

volumes:
  pgdata:
